### ISSUE TITLE
Template Review Feedback

### ISSUE THREAD

**Issue by praveena-pappu** [adglare/gtm#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needs to be resolved ahead of approving the template for the gallery.

1. encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text arguement and return a URI Encoded string. You should use this method on "data.zID", "getTimestamp()" when generating the url
var url = 'https://'+data.domain+'/?' + data.zID + '&cb=' + getTimestamp();

**Comment by adglare** [comment]
Hi @praveena-pappu 

Thanks for reviewing the template - appreciated! The encodeUriComponent() has been applied to the requested parts of the URL meanwhile. The new version/sha has also been added to metadata.yaml. If there's more to change, please let me know.
